-- MySQL Script generated by MySQL Workbench
-- 2017. márc. 22., szerda, 18:33:09 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movies` (
  `id` BIGINT NOT NULL,
  `title` VARCHAR(45) NULL,
  `release` DATE NULL,
  `originality` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`people` ;

CREATE TABLE IF NOT EXISTS `mydb`.`people` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movies_persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movies_persons` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movies_persons` (
  `id` BIGINT NOT NULL,
  `movie_id` BIGINT NOT NULL,
  `person_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `person_id`, `movie_id`),
  INDEX `directors_id_idx` (`person_id` ASC),
  INDEX `movies_id_idx` (`movie_id` ASC),
  CONSTRAINT `movies_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `directors_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'director_id';


-- -----------------------------------------------------
-- Table `mydb`.`leases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`leases` ;

CREATE TABLE IF NOT EXISTS `mydb`.`leases` (
  `id` BIGINT NOT NULL,
  `movie_id` BIGINT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`, `movie_id`),
  INDEX `movie_id_idx` (`movie_id` ASC),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
