CREATE TABLE LEASES
(
  ID BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  MOVIE_ID BIGINT,
  NAME VARCHAR(45) NOT NULL,
  DATE DATE NOT NULL,
  CONSTRAINT MOVIES_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES (ID) ON DELETE CASCADE
)