CREATE TABLE MOVIES_PEOPLE
(
  ID BIGINT PRIMARY KEY NOT NULL,
  MOVIE_ID BIGINT NOT NULL,
  PERSON_ID BIGINT NOT NULL,
  CONSTRAINT MOVIES_PEOPLE_MOVIES_ID_FK FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES (ID),
  CONSTRAINT MOVIES_PEOPLE_PEOPLE_ID_FK FOREIGN KEY (PERSON_ID) REFERENCES PEOPLE (ID)
)